# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_consultdestribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultdestribution',
            name='status',
            field=models.IntegerField(choices=[(1, '正在跟进'), (2, '已成单'), (3, '三天未跟进'), (4, '15天未成单')], default=1),
        ),
    ]
