# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_consult_date',
            field=models.DateField(verbose_name='最后跟进日期'),
        ),
    ]
