# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20171227_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant', to='app01.UserInfo', verbose_name='课程顾问'),
        ),
    ]
