# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20180102_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menue',
            name='title',
            field=models.CharField(max_length=32, verbose_name='菜单名称'),
        ),
    ]
